name: 'Release' 

on:
  release:
    types: 
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_VERSIONING_REGEX: "[0-9]+\\.[0-9]+\\.[0-9]+-[a-zA-Z]+"

  # Project name to pack and publish
  PROJECT_NAME: GeoJSON.Text

   # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  deploy:
    name: 'Deploy to Nuget'
    if: github.event_name == 'release'
    runs-on: windows-2019

    steps:
      - name: Validate release version
        run: |
          $VERSION=${env:GITHUB_REF_NAME}
          if($VERSION[0] -eq "v"){
            $VERSION=$VERSION.substring(1)
          }
          if(!($VERSION -match ${env:NUGET_VERSIONING_REGEX})) {
            throw "Release tag did not contain a valid NUGET version. TAG was : ${env:GITHUB_REF_NAME}"
          }
          echo "Version to use is - $VERSION"
          echo "release_version=$VERSION" | Out-File -FilePath ${env:GITHUB_ENV} -Append
      - name: Release version to build
        run: |
          echo "Release version is ${{ env.release_version }}"